apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bttf
  name: bttf-deployment
  labels:
    app: bttf-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bttf
  template:
    metadata:
      labels:
        app: bttf
    spec:
      containers:
      - name: bttf
        image: acrwesh01devweu.azurecr.io/bttf:v3
        ports:
        - containerPort: 80